kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:19.9.0
    commands:
      - npm install

  - name: test
    image: node:19.9.0
    commands:
      - npm run test:coverage

  - name: build
    image: node:19.9.0
    commands:
      - npm run build
